/** Compatibility facade — implementation lives in `server/af/`. */
export {
  canonicalize,
  closeAirFranceTransport,
  exploreCashFares,
  exploreRewardFares,
  confirmFlyingBlueSession,
  FlyingBlueAuthError,
  importFlyingBlueSession,
  isFlyingBlueAuthenticated,
  mergeCashAndRewardOffers,
  openFlyingBlueLogin,
  parseAvailableOffers,
  parseDailyTopFares,
  parseDailyTopFaresByMonth,
  parseMonthlyFares,
  prewarmCollector,
  searchCashOffers,
  searchRewardOffers,
  solveHashcash,
} from './af/index.js'
